# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'main_windowCwXdoR.ui'
##
## Created by: Qt User Interface Compiler version 6.9.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QComboBox, QGroupBox, QLabel,
    QListView, QMainWindow, QPushButton, QSizePolicy,
    QStatusBar, QWidget)

class Ui_mainWindow(object):
    def setupUi(self, mainWindow):
        if not mainWindow.objectName():
            mainWindow.setObjectName(u"mainWindow")
        mainWindow.resize(1150, 600)
        mainWindow.setMinimumSize(QSize(1150, 600))
        mainWindow.setMaximumSize(QSize(1150, 600))
        palette = QPalette()
        brush = QBrush(QColor(0, 0, 0, 255))
        brush.setStyle(Qt.BrushStyle.SolidPattern)
        palette.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.WindowText, brush)
        brush1 = QBrush(QColor(148, 148, 148, 255))
        brush1.setStyle(Qt.BrushStyle.SolidPattern)
        palette.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Button, brush1)
        brush2 = QBrush(QColor(222, 222, 222, 255))
        brush2.setStyle(Qt.BrushStyle.SolidPattern)
        palette.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Light, brush2)
        brush3 = QBrush(QColor(185, 185, 185, 255))
        brush3.setStyle(Qt.BrushStyle.SolidPattern)
        palette.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Midlight, brush3)
        brush4 = QBrush(QColor(74, 74, 74, 255))
        brush4.setStyle(Qt.BrushStyle.SolidPattern)
        palette.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Dark, brush4)
        brush5 = QBrush(QColor(99, 99, 99, 255))
        brush5.setStyle(Qt.BrushStyle.SolidPattern)
        palette.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Mid, brush5)
        palette.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Text, brush)
        brush6 = QBrush(QColor(255, 255, 255, 255))
        brush6.setStyle(Qt.BrushStyle.SolidPattern)
        palette.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.BrightText, brush6)
        palette.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.ButtonText, brush)
        palette.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Base, brush6)
        palette.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Window, brush1)
        palette.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Shadow, brush)
        palette.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Highlight, brush)
        brush7 = QBrush(QColor(201, 201, 201, 255))
        brush7.setStyle(Qt.BrushStyle.SolidPattern)
        palette.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.AlternateBase, brush7)
        brush8 = QBrush(QColor(255, 255, 220, 255))
        brush8.setStyle(Qt.BrushStyle.SolidPattern)
        palette.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.ToolTipBase, brush8)
        palette.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.ToolTipText, brush)
        brush9 = QBrush(QColor(0, 0, 0, 127))
        brush9.setStyle(Qt.BrushStyle.SolidPattern)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.PlaceholderText, brush9)
#endif
#if QT_VERSION >= QT_VERSION_CHECK(6, 6, 0)
        palette.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Accent, brush6)
#endif
        palette.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.WindowText, brush)
        palette.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Button, brush1)
        palette.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Light, brush2)
        palette.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Midlight, brush3)
        palette.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Dark, brush4)
        palette.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Mid, brush5)
        palette.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Text, brush)
        palette.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.BrightText, brush6)
        palette.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.ButtonText, brush)
        palette.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Base, brush6)
        palette.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Window, brush1)
        palette.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Shadow, brush)
        palette.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Highlight, brush)
        palette.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.AlternateBase, brush7)
        palette.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.ToolTipBase, brush8)
        palette.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.ToolTipText, brush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.PlaceholderText, brush9)
#endif
#if QT_VERSION >= QT_VERSION_CHECK(6, 6, 0)
        palette.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Accent, brush6)
#endif
        palette.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.WindowText, brush4)
        palette.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Button, brush1)
        palette.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Light, brush2)
        palette.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Midlight, brush3)
        palette.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Dark, brush4)
        palette.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Mid, brush5)
        palette.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Text, brush4)
        palette.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.BrightText, brush6)
        palette.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.ButtonText, brush4)
        palette.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Base, brush1)
        palette.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Window, brush1)
        palette.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Shadow, brush)
        palette.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.AlternateBase, brush1)
        palette.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.ToolTipBase, brush8)
        palette.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.ToolTipText, brush)
        brush10 = QBrush(QColor(74, 74, 74, 127))
        brush10.setStyle(Qt.BrushStyle.SolidPattern)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.PlaceholderText, brush10)
#endif
        brush11 = QBrush(QColor(192, 192, 192, 255))
        brush11.setStyle(Qt.BrushStyle.SolidPattern)
#if QT_VERSION >= QT_VERSION_CHECK(6, 6, 0)
        palette.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Accent, brush11)
#endif
        mainWindow.setPalette(palette)
        font = QFont()
        font.setFamilies([u"Arial"])
        font.setPointSize(12)
        mainWindow.setFont(font)
        self.centralwidget = QWidget(mainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.selectButton = QPushButton(self.centralwidget)
        self.selectButton.setObjectName(u"selectButton")
        self.selectButton.setGeometry(QRect(20, 17, 151, 25))
        self.label_2 = QLabel(self.centralwidget)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(375, 400, 311, 23))
        self.equalizationBox = QComboBox(self.centralwidget)
        self.equalizationBox.addItem("")
        self.equalizationBox.addItem("")
        self.equalizationBox.setObjectName(u"equalizationBox")
        self.equalizationBox.setGeometry(QRect(690, 437, 221, 23))
        self.label = QLabel(self.centralwidget)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(375, 437, 331, 23))
        self.applyButton = QPushButton(self.centralwidget)
        self.applyButton.setObjectName(u"applyButton")
        self.applyButton.setGeometry(QRect(530, 494, 241, 25))
        self.saveButton = QPushButton(self.centralwidget)
        self.saveButton.setObjectName(u"saveButton")
        self.saveButton.setGeometry(QRect(530, 530, 241, 25))
        self.filterBox = QComboBox(self.centralwidget)
        self.filterBox.addItem("")
        self.filterBox.addItem("")
        self.filterBox.addItem("")
        self.filterBox.addItem("")
        self.filterBox.setObjectName(u"filterBox")
        self.filterBox.setGeometry(QRect(690, 400, 221, 23))
        self.imageList = QListView(self.centralwidget)
        self.imageList.setObjectName(u"imageList")
        self.imageList.setGeometry(QRect(20, 56, 150, 400))
        self.imageList.setMinimumSize(QSize(150, 250))
        self.imageList.setMaximumSize(QSize(150, 400))
        self.groupBox_3 = QGroupBox(self.centralwidget)
        self.groupBox_3.setObjectName(u"groupBox_3")
        self.groupBox_3.setGeometry(QRect(830, 66, 300, 300))
        self.groupBox_3.setMinimumSize(QSize(300, 300))
        self.groupBox_3.setMaximumSize(QSize(300, 300))
        self.imgEqualizada = QLabel(self.groupBox_3)
        self.imgEqualizada.setObjectName(u"imgEqualizada")
        self.imgEqualizada.setGeometry(QRect(30, 30, 250, 250))
        self.imgEqualizada.setMinimumSize(QSize(250, 250))
        self.imgEqualizada.setMaximumSize(QSize(250, 250))
        self.imgEqualizada.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.groupBox = QGroupBox(self.centralwidget)
        self.groupBox.setObjectName(u"groupBox")
        self.groupBox.setGeometry(QRect(195, 66, 300, 300))
        self.groupBox.setMinimumSize(QSize(300, 300))
        self.groupBox.setMaximumSize(QSize(300, 300))
        self.imgOriginal = QLabel(self.groupBox)
        self.imgOriginal.setObjectName(u"imgOriginal")
        self.imgOriginal.setGeometry(QRect(20, 30, 250, 250))
        self.imgOriginal.setMinimumSize(QSize(250, 250))
        self.imgOriginal.setMaximumSize(QSize(250, 250))
        self.imgOriginal.setLayoutDirection(Qt.LayoutDirection.LeftToRight)
        self.imgOriginal.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.groupBox_2 = QGroupBox(self.centralwidget)
        self.groupBox_2.setObjectName(u"groupBox_2")
        self.groupBox_2.setGeometry(QRect(510, 66, 300, 300))
        self.groupBox_2.setMinimumSize(QSize(300, 300))
        self.groupBox_2.setMaximumSize(QSize(300, 300))
        self.imgFiltrada = QLabel(self.groupBox_2)
        self.imgFiltrada.setObjectName(u"imgFiltrada")
        self.imgFiltrada.setGeometry(QRect(20, 30, 250, 250))
        self.imgFiltrada.setMinimumSize(QSize(250, 250))
        self.imgFiltrada.setMaximumSize(QSize(250, 250))
        self.imgFiltrada.setAlignment(Qt.AlignmentFlag.AlignCenter)
        mainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QStatusBar(mainWindow)
        self.statusbar.setObjectName(u"statusbar")
        mainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(mainWindow)

        self.filterBox.setCurrentIndex(0)


        QMetaObject.connectSlotsByName(mainWindow)
    # setupUi

    def retranslateUi(self, mainWindow):
        mainWindow.setWindowTitle(QCoreApplication.translate("mainWindow", u"Editor de imagens", None))
        self.selectButton.setText(QCoreApplication.translate("mainWindow", u"Selecionar imagens", None))
        self.label_2.setText(QCoreApplication.translate("mainWindow", u"Selecione o filtro para remo\u00e7\u00e3o de ru\u00eddo", None))
        self.equalizationBox.setItemText(0, QCoreApplication.translate("mainWindow", u"Equaliza\u00e7\u00e3o de Histograma", None))
        self.equalizationBox.setItemText(1, QCoreApplication.translate("mainWindow", u"Equaliza\u00e7\u00e3o CLAHE", None))

        self.label.setText(QCoreApplication.translate("mainWindow", u"Selecione a t\u00e9cnica para ajuste de contraste", None))
        self.applyButton.setText(QCoreApplication.translate("mainWindow", u"Aplicar configura\u00e7\u00e3o", None))
        self.saveButton.setText(QCoreApplication.translate("mainWindow", u"Salvar Imagens", None))
        self.filterBox.setItemText(0, QCoreApplication.translate("mainWindow", u"Transformada de Wavelet", None))
        self.filterBox.setItemText(1, QCoreApplication.translate("mainWindow", u"Filtro de Wiener", None))
        self.filterBox.setItemText(2, QCoreApplication.translate("mainWindow", u"Filtro de Mediana", None))
        self.filterBox.setItemText(3, QCoreApplication.translate("mainWindow", u"Difus\u00e3o Anisotr\u00f3pica", None))

        self.groupBox_3.setTitle(QCoreApplication.translate("mainWindow", u"Com ajuste de contraste", None))
        self.imgEqualizada.setText(QCoreApplication.translate("mainWindow", u"Equalizada", None))
        self.groupBox.setTitle(QCoreApplication.translate("mainWindow", u"Imagem original", None))
        self.imgOriginal.setText(QCoreApplication.translate("mainWindow", u"Imagem Original", None))
        self.groupBox_2.setTitle(QCoreApplication.translate("mainWindow", u"Com remo\u00e7\u00e3o de ru\u00eddo", None))
        self.imgFiltrada.setText(QCoreApplication.translate("mainWindow", u"Com tratamento", None))
    # retranslateUi

